import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const menus = [
    {
      label: "HOME"
    },
    {
      label: "ABOUT",
    },
    {
      label: "MY WORK"
    },
    {
      label: "CONTACT",
      classes: "bg-black px-4 py-3 text-white rounded-md"
    }
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main className="container md:max-w-5xl mx-auto px-3">
        <nav className="flex pt-3 items-center">
          <div className="logo">
            <span className='font-semibold'>dytrafolio</span>
          </div>
          <div className="menu-container hidden md:block ml-auto">
            <ul className="flex gap-5">
              {menus.map((menu, index) => {
                return (
                  <li key={index} className="menu-item font-medium"><a href="" className={menu.classes}>{menu.label}</a></li>

                )
              })}
            </ul>
          </div>
        </nav>

        <div className="spacer h-10"></div>
        <div className="hero flex flex-col md:flex-row md:items-center md:gap-20">
          <div className="left md:w-1/2">
            <h1 className="text-5xl text-center md:text-left font-bold">Hi there! 👋</h1>
            <div className="mt-5">
              <div>
                <p className="text-gray-400 text-center md:text-left leading-7">I am a Frontend Web Developer with a passion for creating visually stunning, responsive websites. My expertise includes HTML, CSS, JavaScript, and React. I strive to improve my skills and deliver high-quality, user-friendly websites that meet client and user needs.</p>
              </div>
              <div className="mt-5 flex space-x-3 justify-center md:justify-start">
                <a href="#" className="inline-block bg-primary  text-white rounded-md border border-black px-6 py-3">Work With Me</a>
                <a href="#" className="inline-block bg-brightGrey text-primary border border-primary hover:bg-primary hover:text-white rounded-md px-6 py-3">See My Work</a>
              </div>
            </div>
          </div>
          <div className="right hidden md:block md:w-1/2">
            <div className='w-full py-3'>
              <img src='images/hero.png' className="w-full" />
            </div>
          </div>

        </div>

      </main>
    </>
  )
}
